#include "stm32f10x.h"

#include "FreeRTOS.h"

#include "gpio.h"

#include "neopixel.h"

int main() {
    initNeopixelDriver();

    // Program the LEDs
    uint8_t colors[25] = {NEOPIXEL_COLOR_RED, NEOPIXEL_COLOR_GREEN, NEOPIXEL_COLOR_BLUE, NEOPIXEL_COLOR_WHITE, NEOPIXEL_COLOR_BLACK, NEOPIXEL_COLOR_RED, NEOPIXEL_COLOR_GREEN, NEOPIXEL_COLOR_BLUE, NEOPIXEL_COLOR_WHITE, NEOPIXEL_COLOR_BLACK, NEOPIXEL_COLOR_RED, NEOPIXEL_COLOR_GREEN, NEOPIXEL_COLOR_BLUE, NEOPIXEL_COLOR_WHITE, NEOPIXEL_COLOR_BLACK, NEOPIXEL_COLOR_RED, NEOPIXEL_COLOR_GREEN, NEOPIXEL_COLOR_BLUE, NEOPIXEL_COLOR_WHITE, NEOPIXEL_COLOR_BLACK, NEOPIXEL_COLOR_RED, NEOPIXEL_COLOR_GREEN, NEOPIXEL_COLOR_BLUE, NEOPIXEL_COLOR_WHITE, NEOPIXEL_COLOR_BLACK};
    setNeopixelData(colors, 25);

	while(1) {
        // Do nothing
    }
}